Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: br.com.parcaseparceiros.lambdaeventobuckets.Handler
      CodeUri: D:\Pichau\Documents\parcas-e-parceiros\lambda-bucket
      Runtime: java11
      Architectures:
        - x86_64